---
name: modelling-tasks
extra-source-files:
  - alloy/ad/actionSequencesRules.als
  - alloy/ad/components.als
  - alloy/ad/exerciseRules.als
  - alloy/ad/initialNodeRules.als
  - alloy/ad/nameRules.als
  - alloy/ad/petriNet.als
  - alloy/ad/plantUml.als
  - alloy/ad/reachabilityRules.als
  - alloy/cd/relationshipLimits.als
  - alloy/cd/generate.als
  - alloy/od/template.als
  - alloy/petri/Helpers.als
  - alloy/petri/PetriAdditions.als
  - alloy/petri/PetriConcepts.als
  - alloy/petri/PetriConstraints.als
  - alloy/petri/PetriSignature.als
  - README.md
build-tools:
  - alex
  - happy
ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Widentities
  - -Wredundant-constraints
  - -Werror
  - -Wwarn=x-partial
  - -Wwarn=incomplete-uni-patterns
  - -Wwarn=unrecognised-warning-flags # remove when switching to lts-22 or later
  - -Wwarn=orphans
dependencies:
  - MonadRandom
  - SHA
  - SVGFonts
  - aeson
  - base
  - bimap
  - bytestring
  - call-alloy >= 0.5.0.1 && < 0.6
  - call-plantuml
  - composition
  - containers
  - diagrams-graphviz
  - diagrams-lib
  - diagrams-svg
  - directory
  - edit-distance-vector
  - either
  - exceptions
  - extra
  - fgl
  - file-embed
  - filepath
  - graphviz
  - hgal
  - latex-svg-image
  - lens
  - mtl
  - output-blocks >= 0.2
  - parsec
  - polysemy-plugin
  - random
  - random-shuffle
  - size-based
  - split
  - string-interpolate
  - svg-builder
  - text
  - transformers
  - utf8-string
  - vector
  - hxt
  - xml-conduit
  - yaml
when:
  condition: flag(alloy-use-sat4j)
  cpp-options: -DALLOY_USE_SAT4J
library:
  source-dirs: src
  exposed-modules:
    - Capabilities.Alloy
    - Capabilities.Alloy.IO
    - Capabilities.Cache
    - Capabilities.Cache.IO
    - Capabilities.Diagrams
    - Capabilities.Diagrams.IO
    - Capabilities.Graphviz
    - Capabilities.Graphviz.IO
    - Capabilities.PlantUml
    - Capabilities.PlantUml.IO
    - Modelling.ActivityDiagram.ActionSequences
    - Modelling.ActivityDiagram.Alloy
    - Modelling.ActivityDiagram.Auxiliary.Util
    - Modelling.ActivityDiagram.Auxiliary.Parser
    - Modelling.ActivityDiagram.Config
    - Modelling.ActivityDiagram.Datatype
    - Modelling.ActivityDiagram.EnterAS
    - Modelling.ActivityDiagram.FindSupportST
    - Modelling.ActivityDiagram.Instance
    - Modelling.ActivityDiagram.Isomorphism
    - Modelling.ActivityDiagram.MatchAd
    - Modelling.ActivityDiagram.MatchPetri
    - Modelling.ActivityDiagram.PetriNet
    - Modelling.ActivityDiagram.PlantUMLConverter
    - Modelling.ActivityDiagram.SelectAS
    - Modelling.ActivityDiagram.SelectPetri
    - Modelling.ActivityDiagram.Shuffle
    - Modelling.Auxiliary.Common
    - Modelling.Auxiliary.Output
    - Modelling.CdOd.Auxiliary.Util
    - Modelling.CdOd.CD2Alloy.Transform
    - Modelling.CdOd.CdAndChanges.Instance
    - Modelling.CdOd.CdAndChanges.Transform
    - Modelling.CdOd.DifferentNames
    - Modelling.CdOd.Generate
    - Modelling.CdOd.MatchCdOd
    - Modelling.CdOd.NameCdError
    - Modelling.CdOd.Output
    - Modelling.CdOd.RepairCd
    - Modelling.CdOd.SelectValidCd
    - Modelling.CdOd.Types
    - Modelling.PetriNet.Alloy
    - Modelling.PetriNet.Diagram
    - Modelling.PetriNet.LaTeX
    - Modelling.PetriNet.MatchToMath
    - Modelling.PetriNet.Parser
    - Modelling.PetriNet.Types
    - Modelling.PetriNet.Concurrency
    - Modelling.PetriNet.Conflict
    - Modelling.PetriNet.ConflictPlaces
    - Modelling.PetriNet.Find
    - Modelling.PetriNet.Pick
    - Modelling.PetriNet.Reach.Deadlock
    - Modelling.PetriNet.Reach.Property
    - Modelling.PetriNet.Reach.Reach
    - Modelling.PetriNet.Reach.Step
    - Modelling.PetriNet.Reach.Type
    - Modelling.Types
tests:
  modelling-tasks-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - modelling-tasks
      - QuickCheck
      - HUnit
      - hspec
      - process
      - random
    when:
      - condition: flag(quick-testing)
        cpp-options: -DQUICK_TESTING
flags:
  alloy-use-sat4j:
    description: When calling alloy use the SAT4J SAT solver
    manual: true
    default: false
  quick-testing:
    description: Decreases the testing depth resulting in fewer test cases and thus faster testing
    manual: true
    default: false
