---
name: modelling-tasks-apps
build-tools:
  - alex
  - happy
ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Widentities
  - -Wredundant-constraints
  - -Werror
  - -Wwarn=incomplete-uni-patterns
  - -Wwarn=orphans
dependencies:
  - MonadRandom
  - base
  - containers
  - diagrams-lib
  - diagrams-svg
  - mtl
  - transformers
executables:
  check-cds:
    main: check-cds.hs
    source-dirs: .
    dependencies:
      - autotool-capabilities-io-instances
      - bytestring
      - call-alloy
      - digest
      - graphviz
      - modelling-tasks
    other-modules: [ ]
  conflicts:
    main: conflicts.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - bytestring
      - digest
      - modelling-tasks
      - output-blocks
      - pretty-simple
    other-modules:
      - Common
  concurrency:
    main: concurrency.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - bytestring
      - digest
      - modelling-tasks
      - output-blocks
      - pretty-simple
    other-modules:
      - Common
  different-names:
    main: different-names.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - bytestring
      - digest
      - modelling-tasks
      - output-blocks
    other-modules:
      - EvaluateArgs
      - Common
  enterASTaskDemo:
    main: enterASTaskDemo.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - modelling-tasks
      - output-blocks
    other-modules:
      - Common
  evalIsomorphic:
    main: evalIsomorphic.hs
    source-dirs: .
    dependencies:
      - bytestring
      - call-alloy
      - call-plantuml
      - directory
      - filepath
      - modelling-tasks
      - string-interpolate
  evalTimeToGenerate:
    main: evalTimeToGenerate.hs
    source-dirs: .
    dependencies:
      - call-alloy
      - filepath
      - criterion-measurement
      - modelling-tasks
      - string-interpolate
  findAuxiliaryPetriNodesTaskDemo:
    main: findAuxiliaryPetriNodesTaskDemo.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - modelling-tasks
      - output-blocks
    other-modules:
      - Common
  matchAdTaskDemo:
    main: matchAdTaskDemo.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - modelling-tasks
      - output-blocks
    other-modules:
      - Common
  matchPetriTaskDemo:
    main: matchPetriTaskDemo.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - modelling-tasks
      - output-blocks
    other-modules:
      - Common
  match-cd-od:
    main: match-cd-od.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - bytestring
      - digest
      - modelling-tasks
      - output-blocks
    other-modules:
      - Common
      - EvaluateArgs
  matchToMath:
    main: matchToMath.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - bytestring
      - digest
      - modelling-tasks
      - output-blocks
      - pretty-simple
    other-modules:
      - Common
  repair-incorrect:
    main: repair-incorrect.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - bytestring
      - digest
      - modelling-tasks
      - output-blocks
    other-modules:
      - Common
      - EvaluateArgs
  selectASTaskDemo:
    main: selectASTaskDemo.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - modelling-tasks
      - output-blocks
    other-modules:
      - Common
  selectPetriTaskDemo:
    main: selectPetriTaskDemo.hs
    source-dirs:
      - .
      - common
    dependencies:
      - autotool-capabilities-io-instances
      - modelling-tasks
      - output-blocks
    other-modules:
      - Common
