---
name: Consistency Checks

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

permissions:
  contents: read

jobs:
  consistency:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: stack.yaml has no additions to stack-examples.yaml
        run: "! comm -23 stack.yaml stack-examples.yaml | grep ."

      - name: stack-examples.yaml has no additions to stack-apps.yaml
        run: "! comm -23 stack-examples.yaml stack-apps.yaml | grep ."

      - name: stack-apps.yaml has some additions to stack-example.yaml
        run: "comm -13 stack-examples.yaml stack-apps.yaml | grep ."

      - name: stack-examples.yaml has some additions to stack.yaml
        run: "comm -13 stack.yaml stack-examples.yaml | grep ."

      - name: Check for runaway IO usage in src/ folder
        run: ./scripts/check-no-runaway-io.sh
