---
name: Haskell Linter

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up HLint"
        uses: haskell-actions/hlint-setup@v2
        with:
          version: "3.5"

      - name: "Run HLint"
        uses: haskell-actions/hlint-run@v2
        with:
          path: '["src/", "test/", "app/"]'
          fail-on: suggestion
